#!/usr/bin/perl
use strict;
use warnings;
use FindBin qw($Bin);

opendir D, $Bin;
my @ps = reverse sort grep {/\.ps/} readdir D;
closedir D;

system("gs", '-dNOPAUSE', '-sDEVICE=pdfwrite', '-sOUTPUTFILE=laserctrl.pdf', '-dBATCH', @ps)
	     and die "FAIL";
