#!/usr/bin/perl
use strict;
use warnings;

my @COL = qw(0s 1s);

my $if = "../testdata/out/zoid-color.svg.moves";
open I, "<$if";


my $df = "$if.graph";
open D, ">$df";

my $t = 0;
while (my $line = <I>) {

    my ($id, $duration, $laserI, $laserA, 
	$xs, $xa, $xstart, $xend,
	$ys, $ya, $ystart, $yend,
	$zs, $za, $zstart, $zend,
	$as, $aa, $astart, $aend) = split /\t/, $line;
	my $laserOff = ((!$laserI) and (!$laserA)) ? 1:0;
    
    print D join("\t", $t, $xs, $ys), "\n";
    $t += $duration;
    print D join("\t", $t, $xs+$xa*$duration, $ys+$ya*$duration), "\n";
}
close D;

print "Total time: ".($t/50000)." s \n";

#system("gnuplot", "plot-moves");
